name: Home Assistant for Production

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    env:
      TZ: America/Sao_paulo
      MAILMANAGER: ${{ secrets.MAILMANAGER }}
      SITE_PATH: "/homea/" # ${{ secrets.PORTAINER_PATH }}
      DOMAIN_NAME: ${{ secrets.PORTAINER_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker Compose
        if: always()
        run: docker compose pull

      - name: Stop Docker Compose
        if: always()
        run: docker compose down --remove-orphans
        
      - name: Run Docker Compose Up
        run: docker compose up -d --wait
     
      - name: Views logs
        run: docker compose logs --tail 30

  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      
      - name: 'Install yamllint'
        run: 'pip install yamllint'
        
      - name: 'yamllint version'
        run: 'yamllint --version'
        
      - name: 'Lint YAML files'
        run: 'yamllint --format github .'
